const products = [{
        id: 0,
        name: "Shirt",
        price: 29.99,
        instock: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f1.jpg",
        brand: "adidas",
    },
    {
        id: 1,
        name: "Shirt",
        price: 24.99,
        instock: 43,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f2.jpg",
        brand: "adidas",
    },
    {
        id: 2,
        name: "Shirt",
        price: 19.99,
        instock: 10,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f3.jpg",
        brand: "adidas",
    },
    {
        id: 3,
        name: "Shirt",
        price: 25.99,
        instock: 50,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f4.jpg",
        brand: "adidas",
    },
    {
        id: 4,
        name: "Shirt",
        price: 30.99,
        instock: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f5.jpg",
        brand: "adidas",
    },
    {
        id: 5,
        name: "Shirt",
        price: 32.99,
        instock: 75,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f6.jpg",
        brand: "adidas",
    },
    {
        id: 6,
        name: "Pants",
        price: 30.99,
        instock: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f7.jpg",
        brand: "adidas",
    },
    {
        id: 7,
        name: "Shirt",
        price: 36.99,
        instock: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/f8.jpg",
        brand: "adidas",
    },
    {
        id: 8,
        name: "Shirt",
        price: 19.99,
        instock: 20,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n1.jpg",
        brand: "adidas",
    },
    {
        id: 9,
        name: "Shirt",
        price: 19.99,
        instock: 30,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n2.jpg",
        brand: "adidas",
    },
    {
        id: 10,
        name: "Shirt",
        price: 15.99,
        instock: 5,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n3.jpg",
        brand: "adidas",
    },
    {
        id: 11,
        name: "Shirt",
        price: 16.99,
        instock: 3,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n4.jpg",
        brand: "adidas",
    },
    {
        id: 12,
        name: "Shirt",
        price: 10.99,
        instock: 10,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n5.jpg",
        brand: "adidas",
    },
    {
        id: 13,
        name: "Short",
        price: 20.99,
        instock: 30,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n6.jpg",
        brand: "adidas",
    },
    {
        id: 14,
        name: "Shirt",
        price: 29.99,
        instock: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n7.jpg",
        brand: "adidas",
    },
    {
        id: 15,
        name: "Shirt",
        price: 29.99,
        instock: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        imgSrc: "../img/products/n8.jpg",
        brand: "adidas",
    },
];